# Generated by Django 5.2.6 on 2026-02-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_alter_application_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
