# Generated by Django 5.2.11 on 2026-02-24 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_alter_application_status'),
        ('Students', '0002_remove_student_skills_student_bio_student_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='Jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='Students.student')),
            ],
            options={
                'verbose_name_plural': 'Saved Jobs',
                'unique_together': {('student', 'job')},
            },
        ),
    ]
