# Generated by Django 5.2.6 on 2026-02-11 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('it', 'IT'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('design', 'Design'), ('hr', 'HR'), ('internship', 'Internship')], max_length=50)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part-time'), ('remote', 'Remote'), ('contract', 'Contract')], max_length=50)),
                ('salary', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
