# Generated by Django 5.2.6 on 2026-02-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0004_category_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='job_logos/'),
        ),
    ]
