# Generated by Django 5.2.6 on 2026-02-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0006_category_icon_class_category_slug_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
