# Generated by Django 5.2.6 on 2026-02-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part-time'), ('intern', 'Internship'), ('remote', 'Remote'), ('contract', 'Contract')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=200),
        ),
    ]
