# Generated by Django 5.2.6 on 2026-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0009_student_phone_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
