# Generated by Django 5.2.6 on 2026-02-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0012_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('recruiter', 'Recruiter')], max_length=20),
        ),
    ]
