# Generated by Django 5.2.6 on 2026-02-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0013_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
