# Generated by Django 5.2.6 on 2026-02-23 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0002_recruiter_address_recruiter_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('new_application_alert', models.BooleanField(default=True)),
                ('shortlisted_candidate_alert', models.BooleanField(default=True)),
                ('payment_invoice_alert', models.BooleanField(default=True)),
                ('weekly_report_email', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('default_job_expiry_days', models.PositiveIntegerField(default=30)),
                ('auto_approve_jobs', models.BooleanField(default=False)),
                ('allow_remote_default', models.BooleanField(default=True)),
                ('default_location', models.CharField(blank=True, max_length=255)),
                ('default_salary_visibility', models.BooleanField(default=True)),
                ('show_profile_publicly', models.BooleanField(default=True)),
                ('show_name_publicly', models.BooleanField(default=True)),
                ('allow_direct_messaging', models.BooleanField(default=True)),
                ('allow_candidate_save_company', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
