# Generated by Django 5.2.6 on 2026-02-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
